const ALLOWED_ORIGIN="https://synergistica.in";
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json","access-control-allow-origin":ALLOWED_ORIGIN,"access-control-allow-methods":"POST,OPTIONS","access-control-allow-headers":"content-type"}});
const clean=v=>String(v||"").trim().slice(0,4000);
export default{async fetch(req,env){if(req.method==="OPTIONS")return json({ok:true});if(req.method!=="POST")return json({ok:false,error:"Method not allowed"},405);
 const origin=req.headers.get("origin");if(origin&&origin!==ALLOWED_ORIGIN)return json({ok:false,error:"Origin not allowed"},403);
 try{const form=await req.formData();if(form.get("_honey"))return json({ok:true});
 const type=clean(form.get("form_type"));const now=new Date().toISOString();const id=crypto.randomUUID();
 if(type==="hire"){const data={id,type,created_at:now,name:clean(form.get("Name")),company:clean(form.get("Company")),email:clean(form.get("email")),phone:clean(form.get("Phone")),role:clean(form.get("Role required")),hires:clean(form.get("Number of hires")),location:clean(form.get("Hiring location")),timeline:clean(form.get("Hiring timeline")),budget:clean(form.get("CTC or budget range")),details:clean(form.get("Requirement details"))};if(!data.name||!data.company||!data.email||!data.phone||!data.role||!data.location)return json({ok:false,error:"Please complete required fields."},400);await env.SUBMISSIONS.put("hire/"+now.slice(0,10)+"/"+id+".json",JSON.stringify(data),{httpMetadata:{contentType:"application/json"}});return json({ok:true,id});}
 if(type==="candidate"){const file=form.get("attachment");const data={id,type,created_at:now,name:clean(form.get("Name")),email:clean(form.get("email")),phone:clean(form.get("Phone")),role:clean(form.get("Current role")),experience:clean(form.get("Experience")),current_location:clean(form.get("Current location")),preferred_role:clean(form.get("Preferred role")),preferred_location:clean(form.get("Preferred location")),ctc:clean(form.get("CTC")),notice:clean(form.get("Notice period")),profile:clean(form.get("Profile link")),notes:clean(form.get("Candidate notes"))};if(!data.name||!data.email||!data.phone||!data.current_location||!data.preferred_role)return json({ok:false,error:"Please complete required fields."},400);if(!(file instanceof File)||!file.size)return json({ok:false,error:"Please attach your CV."},400);if(file.size>5*1024*1024)return json({ok:false,error:"CV must be 5 MB or smaller."},413);const ext=(file.name.split(".").pop()||"bin").toLowerCase();if(!["pdf","doc","docx"].includes(ext))return json({ok:false,error:"CV must be PDF, DOC or DOCX."},415);const base="candidate/"+now.slice(0,10)+"/"+id;await env.SUBMISSIONS.put(base+"/profile.json",JSON.stringify({...data,cv:file.name}),{httpMetadata:{contentType:"application/json"}});await env.SUBMISSIONS.put(base+"/cv."+ext,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||"application/octet-stream",contentDisposition:'attachment; filename="'+file.name.replace(/"/g,"")+'"'}});return json({ok:true,id});}
 return json({ok:false,error:"Unknown form."},400);}catch(e){return json({ok:false,error:"Submission service error."},500);}}};